CREATE TABLE IF NOT EXISTS raw_access_record (
    returnObjectId      varchar(12),
    elapseMS            bigint,
    timestamp           bigint,
    via                 text,
    host                text,
    threadId            bigint,
    userAgent           text,
    queryString         varchar(max),
    sessionId           varchar(40),
    xForwardedFor       text,
    requestURL          text,
    userId              integer,
    origin              text,
    date                text,
    method              varchar(10),
    vmId                varchar(60),
    instance            integer,
    stack               text,
    success             boolean,
    responseStatus      integer
);
