CREATE TABLE IF NOT EXISTS raw_access_record (
    returnObjectId      varchar(12)      encode lzo,
    elapseMS            bigint           encode delta32k,
    timestamp           bigint           encode delta32k,
    via                 text             encode lzo,
    host                text             encode lzo,
    threadId            bigint           encode bytedict,
    userAgent           text             encode lzo,
    queryString         varchar(max)     encode lzo,
    sessionId           varchar(40)      encode lzo,
    xForwardedFor       text             encode lzo,
    requestURL          text             encode lzo,
    userId              integer          encode delta32k,
    origin              text             encode lzo,
    date                text             encode lzo,
    method              varchar(10)      encode lzo,
    vmId                varchar(60)      encode lzo,
    instance            integer          encode delta,
    stack               text             encode bytedict,
    success             boolean          encode raw,
    responseStatus      integer          encode bytedict
);
